name: Run Agro News Bot (Hourly)

on:
  schedule:
    # every hour on the hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper against single feed
        run: |
          python NEW_ARG_AGRO_REPORT.py \
            --feed-url https://example.com/my-specific-feed.xml \
            --since-hours 1 \
            --output raw_${{ github.run_number }}.json

      - name: Upload raw output
        uses: actions/upload-artifact@v3
        with:
          name: agro-hourly-raw-${{ github.run_number }}
          path: raw_*.json
          retention-days: 1
