name: Run Agro News Bot (hourly)

on:
  schedule:
    - cron: '0 * * * *'  # every hour on the hour
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python NEW_ARG_AGRO_REPORT.py --since-hours 1.5 #-- since-days 1

      - name: Set timestamp env var
        run: echo "TIMESTAMP=$(date +'%Y_%m_%d__%H_%M')" >> $GITHUB_ENV

      - name: Upload JSON files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: news-json-${{ env.TIMESTAMP }}
          path: HOURLY_JSON/news_hourly.json