name: Run Agro News Bot (daily)

on:
  schedule:
    - cron: '0 12 * * *'  # ⏰ Every day at 9:00 AM Argentina (12:00 UTC)
  workflow_dispatch:     # Optional: manually trigger from GitHub if you want

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip  # Explicitly upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt  # Point to the root directory

      - name: Run script
        run: python daily_agro_scraper.py
