name: Test Upload Artifact 10

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test content" > test.txt
      - name: Upload artifact
        uses: actions/upload-artifact@b6b27b4c18df34d5510c6a4209a41dfd3a2d4aa5
        with:
          name: test-artifact
          path: test.txt
