name: Test Upload Artifact 1
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test content" > test.txt
      - name: Upload artifact alternative
        uses: dawidd6/action-upload-artifact@v1
        with:
          name: test-artifact
          path: test.txt
