name: Test Upload Artifact 10

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test content" > test.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test-artifact
          path: test.txt
