name: Weekly Agro Summary

on:
  schedule:
    - cron: '5 12 * * 1'  # ⏰ Every Monday at 12:05 UTC (9:05 AM Argentina)
  workflow_dispatch:

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download all raw JSON artifacts
        uses: actions/download-artifact@v4
        with:
          path: raw/

      - name: Merge, dedupe & send email
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          SENDER_EMAIL:     ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD:  ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL:  ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          python summary_and_email.py raw/
